In [15]:
import numpy as np

In [16]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [17]:
np.save('myarray',arr)

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
print np.load('myarray.npy')


[0 1 2 3 4]


In [20]:
arr1 = np.load('myarray.npy')
arr1 

array([0, 1, 2, 3, 4])

In [21]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [23]:
archive_array = np.load('ziparray.npz')
archive_array['x']

array([0, 1, 2, 3, 4])

In [24]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [31]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])