In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame, read_html

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=list('TUV'))
ser2 = Series([0,1],index=list('XY'))

In [8]:
ser1 

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    0
Y    1
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    0
Y    1
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1) # Create data frame

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   0
Y NaN   1

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    0
      Y    1
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=list('XYZ'))
dframe2 = DataFrame(np.random.randn(3,3),columns=list('YQX'))

In [14]:
dframe1

X         Y         Z
0  0.408807 -0.484614 -0.783355
1  0.198446  0.548114 -0.575908
2 -0.147782 -1.502024  0.956378
3  0.646749 -0.255270 -2.541646

In [15]:
dframe2

Y         Q         X
0 -0.345152  2.227029  0.840226
1  0.442739  0.676166  1.709841
2  1.280795  0.158905 -0.030939

In [17]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.408807 -0.484614 -0.783355
1       NaN  0.198446  0.548114 -0.575908
2       NaN -0.147782 -1.502024  0.956378
3       NaN  0.646749 -0.255270 -2.541646
0  2.227029  0.840226 -0.345152       NaN
1  0.676166  1.709841  0.442739       NaN
2  0.158905 -0.030939  1.280795       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.408807 -0.484614 -0.783355
1       NaN  0.198446  0.548114 -0.575908
2       NaN -0.147782 -1.502024  0.956378
3       NaN  0.646749 -0.255270 -2.541646
4  2.227029  0.840226 -0.345152       NaN
5  0.676166  1.709841  0.442739       NaN
6  0.158905 -0.030939  1.280795       NaN

In [ ]:
#http://pandas.pydata.org/pandas-docs/stable/generated/pandas.tools.merge.concat.html