In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10) # normal distribution 
A

array([ 0.45612818, -1.11180628,  0.34331153,  0.8419985 ,  0.63435726,
       -0.94815492,  0.69484208,  0.78924315,  0.12169512,  0.07335858])

In [7]:
B = np.random.randn(10) # normal distribution 
B

array([ 1.54973295, -1.69842083,  1.28131812, -0.7151962 , -1.16402902,
       -1.48827335, -2.28115813,  0.88292158, -2.97929059,  0.15225034])

In [8]:
#Binary Function
np.add(A,B)

array([ 2.00586112, -2.81022711,  1.62462964,  0.1268023 , -0.52967175,
       -2.43642826, -1.58631605,  1.67216473, -2.85759547,  0.22560892])

In [10]:
# Get the max elements pair of (A,B)
np.maximum(A,B)

array([ 1.54973295, -1.11180628,  1.28131812,  0.8419985 ,  0.63435726,
       -0.94815492,  0.69484208,  0.88292158,  0.12169512,  0.15225034])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True