In [1]:
import numpy as np

In [2]:
5/2

2

In [4]:
from __future__ import division # for python 2.x

In [5]:
5/2

2.5

In [7]:
arr1 = np.array([[1,2,3,4],[7,8,9,10]])

In [8]:
arr1

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [9]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 49,  64,  81, 100]])

In [10]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.14285714,  0.125     ,  0.11111111,  0.1       ]])

In [11]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 343,  512,  729, 1000]])