In [3]:
import numpy as np
my_list1 = [1,2,3,4]
my_list2 = [11,22,33,44]

my_array1 = np.array(my_list1)

my_lists = [my_list1,my_list2]

my_array2= np.array(my_lists)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
my_array2.shape

(2L, 4L)

In [9]:
my_array2.dtype

dtype('int32')

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
my_zeros_array = np.zeros(3)
my_zeros_array.dtype

dtype('float64')

In [12]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
np.empty(5)

array([  2.92383543e-316,   1.99819870e-316,   1.49251659e-316,
         3.10290419e-316,   3.12807189e-316])

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])